name: Build ArchISO

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Build ISO
        run: |
          docker run --privileged --rm \
            -v "$PWD":/work \
            -w /work \
            archlinux:latest \
            /bin/bash -c "
              pacman -Syu --noconfirm archiso git && \
              chmod +x build.sh && \
              ./build.sh
            "

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: archlinux-custom-iso
          path: out/*.iso
          if-no-files-found: error
          compression-level: 0
          retention-days: 30